ChameleonCloud/portal

- chameleon/templates/home.html
- djangoRT/forms.py
- djangoRT/rtUtil.py
- djangoRT/templates/ticketCreate.html
- djangoRT/templates/ticketCreateGuest.html
- djangoRT/templates/ticketReply.html
- djangoRT/views.py
- documentation/data/getting-started.md
- documentation/data/index.md
I added support for attachments, need to test it on development. We are having some issues with the RT instance and it would be faster for Mike Packard to be able to see what's going on rather than having to talk to me while debugging.
> Ticket attachments

- Dockerfile
- chameleon/settings.py
- documentation/data/user-guides/index.md
- locale/en/LC_MESSAGES/django.po
- Added console access to alamo user guide.
I didn't know how to not include this in my pull request; but maybe it's no biggie:
- Added ironic user guide. This is not ready for user consumption yet, but it's not linked anywhere. So probably fine to publish?
> minor doc changes

- g5k_discovery/scripts/controllers/modal_controller.js
This pull request proposes a fix for an issue encountered during the generation of a "climate" lease command: start time and end time were reversed.
> fix a bug where start time and end time of a lease command were mixed;

- projects/views.py
If everything looks good, can you send this change to prod with the sharing-portal updates
> populating keystone project description from tas

- chameleon/settings.py
- chameleon/templates/includes/header.html
- chameleon/templates/includes/navigation.html
- chameleon/urls.py
- chameleon_cms_integrations/cms_apps.py
- chameleon_cms_integrations/cms_menus.py
- static/styles/_chameleon.scss
- static/styles/_vars.scss
> New top-level menu

- appliance_catalog/views.py
Add a hook to send messages to GA for tracking the downloads of complex appliances.
> google analytics measurement protocol

- sharing_portal/models.py
- sharing_portal/views.py
See commit messages for details.
> Add fixes relevant for sharing multiple versions

- util/project_allocation_mapper.py
We only took in to account "used" SUs, which are for leases that have
terminated. We also need to count the leases that are currently active.
> Fixup display of SU usage

- util/project_allocation_mapper.py
Saving projects to TAS will not create project in keycloak, and thus
users will miss their newly created project in the dashboard.
> save all projects/allocations to portal and keycloak

- util/project_allocation_mapper.py
Since all project and allocation requests will not go to TAS, need to
fetch and approve projects via portal only.
> use portal for project fetching and approval

- allocations/tasks.py
- util/keycloak_client.py
Beyond just the allocation balance, we sometimes need to know the
standing of a project. There is no way to enable/disable a group in
Keycloak, so instead we must add an additional piece of metadata and
keep it in sync w/ the allocation. We expire and activate allocations
via this task mechanism, so that's where this logic lives.
> Set flag on Keycloak groups w/ active alloc

- util/project_allocation_mapper.py
separated method for getting sortable key from allocation
used for sorting both allocations and projects
Extends fix from https://github.com/ChameleonCloud/portal/pull/107
> sort order of allocations by request date.

- chameleon/admin.py
Try to parse ORCID ID from availble user info.
TODO
This is a stopgap, we should get authenticated user info
on sign in, and attach it to their accounts.
> Render orcid ID as clickable link if available

- chameleon/settings.py
missed a set of lines from another PR.
> disable browsable API in prod

- allocations/templates/allocations/index.html
- allocations/templates/allocations/user-projects.html
Show the allocation reviewer username.
Also auto-formatted HTML templates.
> show allocation reviewer username

- allocations/models.py
- chameleon/__init__.py
- chameleon/models.py
- chameleon/wsgi.py
- projects/__init__.py
- projects/apps.py
- projects/forms.py
- projects/models.py
- projects/monkey_patching.py
- projects/templates/projects/view_project.html
- projects/views.py
- util/project_allocation_mapper.py
If the PI knows the email address, this allows them to add a user to the project based on the email address.
This also includes some refactorings in here to continue ripping out crufty TAS code.
> Allow adding users to project by email address

- util/project_allocation_mapper.py
The implementation before this commit will create a RT ticket but not
send the message to the PI. Need to create a ticket, and then reply.
> create ticket and send message

- yarn.lock
Hopefully close a lot of dependabot deps.
this is the output of running `yarn upgrade`
> update node deps

- g5k_discovery/templates/g5k_discovery/discovery.html
Links were changed during the calendar rewrite.
> Update calendar links

- djangoRT/tasks.py
- djangoRT/views.py
Now, the ticket is submitted to RT before calling any openstack functions. Then celery will asynchronously add the openstack data as a comment to the ticket.
> Fix rt timeout caused by gathering openstack data for a user

- sharing_portal/templates/sharing_portal/request_day_pass.html
- sharing_portal/templates/sharing_portal/review_day_pass.html
- sharing_portal/views.py
This should hopefully make it clearer to a user what to do when they receive approved day pass.
> Update day pass wording

- g5k_discovery/templates/g5k_discovery/discovery.html
This PR adds NCAR to the list of availability calendars, and fixes a broken link to each site.
> Add ncar site, fix broken links

- g5k_discovery/templates/g5k_discovery/discovery.html
Add EVL host calendar. However, this shouldn't be merged until they have their site in reference-repository.
> add EVL calendar

- g5k_discovery/templates/g5k_discovery/discovery.html
> with 5 sites, 5*3>12, so we overflowed!

- sharing_portal/static/sharing_portal/index.js
- sharing_portal/views.py
This improves the search feature of trovi, and clears up the launch button missing for a logged out user.
> Trovi usability

- sharing_portal/views.py
The relevant code got moved to the except block, and so would not run
correctly.
> Fix bug creating daypass project

- projects/pub_views.py
We'd like to manually review user publications as soon as they are
entered. So after new user publications are successfully imported
to the portal DB, a notification will be sent to an internal
mailing list. We also make creating multiple publications an atomic
transaction to prevent duplications.
> send notification when user adds publications

- projects/migrations/0019_publication_sources_with_data_migrationshell.py
- projects/migrations/0020_duplicate_publications.py
- projects/models.py
and remove the not working constraint `if the publication is approved then approved_with must have a value` 
Fails with error - "Joined field references are not permitted in this query"
> Fix the source fields in Publication model

- projects/tasks.py
- sharing_portal/templates/sharing_portal/detail.html
- sharing_portal/templates/sharing_portal/review_daypass.html
- sharing_portal/trovi.py
- sharing_portal/urls.py
- sharing_portal/views.py
Daypass has been mostly broken since we overhauled Trovi. This patch fixes various errors which prevented Daypass from working.
> Fix issues with Daypass error handling

- projects/forms.py
- projects/pub_views.py
- projects/templates/projects/add_publications.html
- projects/templates/projects/view_project.html
We would like to make it easy for users to submit publications, the backend we anyway verify the authenticity.
Tested locally and in dev (with `PermissionDenied` changes too)
> Allow any user to upload publications

- balance_service/utils/openstack/keystone.py
- balance_service/views.py
Only the Billing error is being caught and an appropriate message is being propagated from the exception. Fix is to catch all the `EnforcementException`s
> Fix enforcement exception propagation

- sharing_portal/forms.py
This is already enforced server side, but need to set the limit in forms too
> Set a limit to charachters in trovi artifact title and short description

- allocations/tasks.py
The allocation system now logs when allocations are activated and deactivated.
> Add allocation expiration/activation logging

- allocations/tasks.py
In the code where consistency errors were reported, they are now also corrected.
> Correct Keycloak consistency errors in Allocation tasks

- README.md
- sharing_portal/templates/sharing_portal/detail.html
- sharing_portal/tests/test_git_parser.py
- sharing_portal/views.py
This is when artifact contains github url
> Feedback button which redirects to github issues

- projects/admin.py
This change makes it easy to filter and view publications to review based on status
> Show status field in the admin interface to review publications

- projects/models.py
- projects/user_publication/deduplicate.py
- projects/user_publication/publications.py
include pub admin page url in the pub repr method
> Save after reviewing duplicates

- allocations/models.py
- sharing_portal/templates/sharing_portal/index.html
- sharing_portal/views.py
Do not show a private icon if any of the versions have a DOI
add has_doi field to the artifact by looking at versions for doi
> Donot show private icon if doi

- sharing_portal/views.py
They are getting tagged as 'Others'
> Daypass projects must be tagged as 'Daypass'

- projects/static/projects/css/projects.scss
- projects/templates/projects/view_project.html
- projects/urls.py
- projects/views.py
PIs have requested to be able to export a list of project members. This adds a button that downloads a CSV file with member information.
> Add project member export feature

- allocations/admin.py
- allocations/static/allocations/js/admin.js
I previously assumed the contact endpoint was expecting the ID, but this is incorrect. It instead needs direct access to the PI email. This was hard to debug because all of the old code is in untouched angular stuff.
> Fix contact pi form

- projects/user_publication/gscholar.py
- projects/user_publication/publications.py
- projects/user_publication/scopus.py
This code is just too dependent on outside data to be reliable. Lots of random errors pop-up due to data validation in django/mariadb. This wraps everything in a try/except so that if any one publication causes problems, we can ignore it.
> Wrap all publication stuff in try/except

- chameleon/vue/frontpage_carousel.css
- projects/pub_views.py
- projects/templates/projects/chameleon_used_in_research.html
- static/styles/_chameleon.scss
Updates to research papers/impacts page. Fixes to home page
> Portal UI updates

- djangoRT/rtUtil.py
- projects/admin.py
- projects/forms.py
- projects/pub_views.py
- projects/templates/projects/add_publications.html
- projects/util.py
Improvements to the publication create page that requires the user to submit a URL and pick a confirmation option.
Also when a publication is reviewed, automatically closes the Django Ticket associated with it.
> Publication create improvements

- allocations/admin.py
- projects/static/projects/js/fundings.js
- projects/templates/projects/fundings.html
- projects/views.py
Add required dropdown to confirm funding
> Update allocation form with funding dropdown
