chameleon/urls.py, chameleon_mailman/views.py
The new sync behavior will be to sync only members who have recently
signed up with Chameleon. This updates the sync endpoint to not be
list-specific, and also to only pull users who have joined since the
beginning of the day. As long as this runs once a day, we shouldn't miss
anybody.
=> Update mailman sync to look at only new users

projects/views.py
This feature update allows user creation in Keystone even if the user has not completed email confirmation
=> Using TAS data to create ks users

chameleon/templates/sso/keystone_login_unavailable.html, chameleon/templates/sso/keystone_project_not_found.html, chameleon/urls.py, chameleon/views.py
The login loop may have surfaced when a token was retrieved successfully at the manual login form, but an error occurred when synchronizing projects. The error sent the user to `manual_ks_login(request)` where, if the original request method was POST, the function then interpreted the request as a form submission and tried to get a new token, then looped back to attempt project sync where the same failure as before caused another call to `manual_ks_login(request)`, causing a loop in Django
=> Ensuring no redirect loop on form post and Horizon SSO

sharing_portal/urls.py, sharing_portal/views.py
The JupyterHub integration doesn't know about sharing portal IDs, nor
should it. However, it does know about DOIs, and we can use this allow
linking out to an edit page.
This adds a new route that will attempt to look up an artifact by DOI
and open its edit page.
=> Add support for editing given DOI

chameleon/os_login.py, chameleon/views.py, djangoRT/views.py, projects/views.py
When making calls to OpenStack via its clients, it's possible to pass in
a Session object, which contains the auth information and other params.
However, you can also pass in an Adapter, which wraps a session but
pre-fills a few things that would normally be specified per-call or
per-client-construction, such as which interface/region to use (which
endpoint).
This updates all of the keystone clients to use Adapters with
interface=public and region pre-filled (where applicable.)
=> Include interface/region in session adapter

chameleon/__init__.py, chameleon/celery.py, chameleon/settings.py, chameleon_mailman/models.py, chameleon_mailman/tasks.py, docker-compose.dev.yml, docker-compose.yml, requirements-frozen.txt, requirements.txt, upper-constraints.txt, user_news/forms.py, user_news/models.py
Gives admins option to send outage email reminders by specified number of
seconds before outage (current set to 2 hours in settings file). This
required adding celery and redis as a broker and backend.
=> Add outage email reminders

chameleon/views.py, projects/views.py
This change tags on to project sync during SSO to ensure PI's and their projects exist in Keystone before trying to log them in to Horizon
=> Ensuring new projects and PI's exist in Keystone

.gitignore, tas/forms.py, tas/views.py
Updating user profile form to disable profile info changes (excluding pi eligibility request) when user authenticated via Keycloak.
=> Disallow editing user profile when using fed auth

tas/forms.py, tas/views.py
User profile information is currently pulled from TAS. This should change when using federated auth for login. When using the federated auth flow users should see user profile information retrieved from Keycloak
=> Change User Profile data source when using Federated Auth

util/project_allocation_mapper.py
Currently any user with the "superuser" status is exposed to the new
projects/allocations code. To make this easier to test, make it easy to
opt-in/opt-out by making it linked to federated vs. non-federated login
sessions.
Users can log in via federation at /oidc/authenticate
=> Use mapped projects/allocations only for fed users

chameleon/os_login.py, chameleon/settings.py, chameleon/urls.py, chameleon/views.py
Because it is possible to set cookies on all subdomains by using a
leading '.' on the cookie domain, we can effectively opt a user in to
all web properties via a single endpoint.
This also supports an opt-out flow.
To opt in, visit: /new-login-experience
To opt out, visit: /new-login-experience?opt-out
=> Add toggle for opting in globally to federation

util/project_allocation_mapper.py
When we get a project from portal, although we switch the project as TAS Project object, we keep the portal project id. But this will mess up getting members of a project https://github.com/ChameleonCloud/portal/blob/master/util/project_allocation_mapper.py#L285-L287.
=> fix issue of listing random users in a project

allocations/models.py, projects/models.py, util/project_allocation_mapper.py
Loading all projects/allocations is slow in admin page. The cause of the
slowness is due to the django model foreign key lazy load. To improve the
performace, django "select_related" is used. The django "select_related"
is a performance booster which results in a single more complex query but
means later use of foreign-key relationships won’t require database queries.
Read https://docs.djangoproject.com/en/2.2/ref/models/querysets/#select-related
for more information.
=> improve admin projects/allocations loading

chameleon/admin.py, tas/views.py, util/keycloak_client.py, util/project_allocation_mapper.py
Portal doesn't store all metadata of a user. To provide the user
information for pi eligibility reviewers and to show profile in the user
dashboard, we fetch user metadata from Keycloak.
=> show user metadata in pi eligibility review page and profile page

tas/forms.py, tas/templates/tas/profile_edit.html, util/project_allocation_mapper.py
- If the user did not have citizenship defined, the form would fail b/c
this was a required field but the user could not edit
To fix this, this overhauls the edit form. We now handle empty
citizenship and ask the user here. There were issues mapping Keycloak
countries to the TAS list; drop the TAS list and settle on ISO-3166,
which is used in the Keycloak form. Also stop asking for institutions
and departments, which could not match anymore.
=> Fix issues requesting PI eligibility

chameleon_mailman/tasks.py
Outage reminder emails were being sent without html formatting.
This was because only plain_text was being passed to django's
send_mail function. To preserve html formatting for the email
message the message body should be passed to html_message kwarg.
=> Add html_message kwarg to outage reminder mail.

sharing_portal/forms.py, sharing_portal/views.py
This updates the edit UI to allow updating artifact labels. These labels
can be updated either within the embedded Jupyter edit form or on Trovi.
This functionality already existed, but was never surfaced to the user.
=> Enable managing artifact labels

.github/actions/yamllint.yml, .github/workflows/lint-ansible.yml, .github/workflows/lint-docker.yml, .github/workflows/lint-javascript.yml, .github/workflows/lint-python.yml, .github/workflows/lint-shell.yml, .github/workflows/lint-spelling.yml, .github/workflows/lint-style.yml, .github/workflows/lint-yaml.yml, pyproject.toml
We want to enable automatic code checks
Initially, the tools black and pylint are supported.
Reviewdog outputs these changes as github checks, as well
as suggesting changes on PR review
Configuration for linters is stored in pyproject.toml
=> Enable automatic linting

allocations/urls.py, allocations/views.py
This adds an extra view to return the raw json for offline analysis.
Example jq query to get total usage per project:
cat usage_data.json | jq '.[] | {chargeCode: ."chargeCode", type: .type, totalusage: [.allocations[].computeUsed] | add}'
Schema already offers "type", with values "startup, research, educational"
I assume we need to filter by year.
=> add extra view to return raw json dump

pyproject.toml, tox.ini
Black and Flake8 config to be compatible with django projects.
Flake8 currently cannot be configured via pyproject.toml,
but many projects already have a tox.ini file.
Line length could be adjusted higher, up to 119 for code, and 79 for
docs as per:
https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#python-style
=> add exclusions for django migrations

docker-compose.yml
Added some health checks to improve the robustness of the local development environment.
There was often a race between the mysql container and celery.
Health check added to portal container, just to ensure the service is listening.
=> Make docker for local dev more robust

chameleon/settings.py, upper-constraints.txt, util/sql_format.py
This PR fixes sql logging in Django.
We needed to pin the mysql client version.
The Django SQL logs then expose the query explicitly.
Adds a Formatter to optionally pretty-print queries.
=> pretty-print sql logs

.env.sample, .gitignore, Makefile, chameleon/settings.py, docker-compose.yml, util/sql_format.py
There's a bit of noise in the PR due to the auto-formatter, I can clean that up into two commits if needed.
The purpose of this PR is to:
1. Clean up the logging configuration for easier debugging.
2. Put configuration paramaters that are common to both the makefile, docker-compose file, and running container, into the .chameleon_env file
3. rename .chameleon_env to .env, so that docker-compose will automatically use it without specifying --env-file
4. add a valid .sample.env to the repo, so that local development has fewer manual steps
5. add a target to the makefile to copy .sample.env -> .env if missing
=> Use same .env file for docker-compose and makefile.

sharing_portal/forms.py, sharing_portal/models.py, sharing_portal/static/sharing_portal/artifacts.css, sharing_portal/templates/sharing_portal/includes/stats.html, sharing_portal/views.py
An artifact is Chameleon supported if the Chameleon team is reponsible
for maintenance. This is indicated via a special label named "chameleon".
If that label is set, an additional icon is included in the tag labels
UI section. This label can only be set by Portal staff members and
normal users do not even see it.
=> Add notion of Chameleon-supported artifacts

chameleon/settings.py, djangoRT/admin.py, djangoRT/forms.py, djangoRT/models.py, djangoRT/rtModels.py, djangoRT/rtUtil.py, djangoRT/templates/djangoRT/attachment.html, djangoRT/urls.py, djangoRT/views.py
This is a general refactor of the RT app, but just the view layer.
This moves most of the ticket handling logic to a core function, which
is called for both the logged in and guest case. Also fixes a bug where
mimetype was set to a tuple and not a string, which apparently caused
RT to throw its hands in the air and not process the file properly.
Added some better/more consistent error messaging, and ensured that
Python warnings were making it to the logging infra--the RT client uses
this mechanism to emit errors, so it's important we are seeing them.
=> Fixup RT ticket views

.env.sample, chameleon/settings.py
Adding recaptcha involved defining CSP_FRAME_SRC, but it was missing "self".
In addition, default keys have been defined for recaptcha. If used, recaptcha will always pass, and display a graphical warning.
In addition, the changes to ALLOWED_HOSTS from the recent domain change no longer allowed setting it from the .env file.
This fixes a typo, and allows setting via .env file.
=> Fix allowed_hosts and CSP=self for recaptcha

chameleon/settings.py
Requests are coming from the host namespace on chameleon06
The "correct" way to handle this is to fix whatever is sending the
request to use the app docker network
A second issue is our usage of os.envion.get, since it has issues
with non-string data types.
We should use a library like `environs` to handle list types.
=> quick-fix Allow requests from prod's host IP

djangoRT/templates/djangoRT/project_details.txt, djangoRT/views.py, poetry.lock, pyproject.toml, util/keycloak_client.py
Project, lease, and instance information is added to the end of
a ticket submitted by a logged in user. If a user is anonymous,
no information is displayed.
The version of python-blazarclient is switched to use Chameleon's
version of this library, so that `list_allocations` can be used.
Also, python-ironicclient is added as a new dependency to get the
provision state and instance uuid of a reserved node. This should
make it easier to find the issue when a node in a user's lease
won't launch.
=> Add Openstack information in RT ticket description

allocations/tasks.py
If multiple allocations exist, previously the one with the earlier
expiration date is made inactive. This updates the allocation
expiration date along with this inactive update.
=> Update allocation expiration date is set if multiple allocations exist

chameleon/os_login.py
When redirected to login for a page that requires it, the next URL
parameter is used to remember the place. However, this was lost
when issuing a redirect to 'oidc_authentication_init'. This patch
fixes this issue by manually adding it to the oidc path when
generating the redirect.
=> Fix next param getting lost on login redirect

chameleon/templates/dashboard.html, chameleon/views.py
This banner seems to be confusing to users, and is perhaps misleading.
=> Remove legacy account warning banner from dashboard

Dockerfile, chameleon/settings.py
I've updated the cms pages that were using these, and now they can be removed.
=> Remove legacy plugins

sharing_portal/views.py
This fixes `'ShareTarget' object has no attribute 'charge_code'` error when an artifact was shared with a project.
It also filters deleted artifacts. There is no UI to do this, but an admin can set this via the admin panel.
=> Fix sharing portal project sharing and filter deleted projects

chameleon_mailman/tasks.py, user_news/models.py
When sending outage reminders, `reminder_sent` is checked for null. When an outage is saved that is scheduled for
within 1 day, we set this to the current date to avoid the task sending an email in the future.
=> Add check to ignore reminder email for outage starting within one day

sharing_portal/static/sharing_portal/artifacts.css, sharing_portal/templates/sharing_portal/edit.html, sharing_portal/views.py
Adds a button to delete all artifact versions, and then the artifact itself. The button is accessible via the edit page for a given artifact. Currently, it will launch a JavaScript prompt that will ask for the name of the artifact to confirm its deletion. It will wait until the correct name is input, or the prompt is cancelled.
This achieves the desired function of the confirmation prompt, but I think it would be more ideal to mimic the behavior of other websites (such as deleting a repo on GitHub) where a prompt pops up, and the confirm button is greyed out until the text in the box matches the desired input. I think this is more familiar to users, but unfortunately seems like a challenging front end task, which I am not very familiar with.
Some additional refactoring to the version …
=> Allow deleting entire Trovi artifact

allocations/templates/allocations/index.html, allocations/views.py, projects/templates/projects/allocation.html, projects/templates/projects/create_project.html, util/keycloak_client.py
we'd like to grant pi eligibility to international researchers,
but have more restrict rules to approve their allocation requests.
in order to easily tell if the project belongs to an international
pi, the allocation admin page will display the institution and country
of the pi. The information is collected from keycloak.
=> display institution and country of the pi

allocations/tasks.py, allocations/utils.py, balance_service/enforcement/usage_enforcement.py
when creating a new charge record, a temporary resource id is given.
a periodic task finds the actual reservation id and replace the
temporary one. However, getting the reservation id based on
project_id, user_id, lease_start_date is not enough, so lease name
condition is added.
=> fix for getting resource id

projects/membership.py, projects/views.py, util/keycloak_client.py, util/project_allocation_mapper.py
We'd like to start tracking when users join their first allocation for usage reporting purposes. It helps to know how many users are actually part of an allocation, and what is the delta b/w when they signed up, and when they finally were added to an allocation (if at all.)
=> Add field on user when joining allocation for the first time

allocations/templates/allocations/approval.html, allocations/templates/allocations/index.html, chameleon/admin.py, static/scripts/cannedresponses.js
Currently, all canned pi eligibility and allocation review
responses are stored in a google doc and the responses are
copied and pasted everytime. We would like to have a better
centralized location for the canned responses. Since the
responses are used exclusively with portal, we'll use the
portal to store them. Also, add some javascript functions
for auto-filling based on the selections.
=> Store canned approval responses in portal

sharing_portal/tasks.py, sharing_portal/trovi.py
Simple fix which syncs the dates for versions to Trovi. I tested this and it works, but there were a couple versions which caused errors on the second run because they tried to add a version which already existed.
=> Sync version dates in artifact migration script

sharing_portal/trovi.py, sharing_portal/views.py
Portal now fetches the contents download URL from Trovi and passes it on to JupyterHub in the form of a URL parameter
=> Fix trovi content download

chameleon/settings.py
Django defaults to one week. It's important that this matches our SSO
session lengths in Keycloak to avoid the Keycloak token expiring in the
background.
=> Decrease session age to 7 days

docker-compose.yml, sharing_portal/static/sharing_portal/artifacts.css, sharing_portal/templates/sharing_portal/detail.html, sharing_portal/urls.py, sharing_portal/views.py
This hooks up Trovi's contents endpoint to the side panel on the detail page for artifacts.
Here is an artifact from github, so it has the HTTP archive download, and the git information
One issue with redirecting users to the HTTP url directly is that swift URLs downloads a file named just the UUID, with no extension, and the mime type was set to plain text. So my experience was that after downloading in chrome, I clicked on the file, and it opened in a text editor, but it worked fine opening with the archive manager.
=> Trovi download archive

sharing_portal/static/sharing_portal/artifacts.css, sharing_portal/static/sharing_portal/tooltip.js, sharing_portal/templates/sharing_portal/detail.html, sharing_portal/templates/sharing_portal/index.html, sharing_portal/views.py
This shows an icon next to an artifact title when the artifact is private. The only other place this information is displayed is inside the sharing settings.
List view:
Detail view:
=> Add private icon next to a private artifact

chameleon/settings.py
Local dev environments will not have this config, nor should they really.
However, not having this config means DB migrations cannot work (the
charge table migration will try to copy data from an external source.)
This will drop the region config from the dict if it's not defined on the
env, using the host field as the heuristic. Otherwise weird typeerrors
get raised when connecting to the DB.
=> Handle missing openstack region config

g5k_discovery/templates/g5k_discovery/discovery.html, g5k_discovery/templates/g5k_discovery/node_details.html, g5k_discovery/vue/HardwareCatalogueFilters.vue, g5k_discovery/vue/HardwareDetails.vue, g5k_discovery/vue/InfiniteScroller.vue
1. Replace human-friendly node type “summaries” with the actual node types in the big green box. Users are already confused about this enough, I think we can just stick to node type as a general filter mechanism.
2. Make the top line of buttons NOT green so they’re not semantically linked w/ the below buttons, which act as filters (the top row are all external links!)
3. Add the node type as a label in the details view so you can easily see which nodes are of which type.
4. Tightened up the headings a bit and renamed to match menu nav terminology.
=> Clean up hardware browser UI

chameleon/settings.py
Our images are uploaded either while on chameleoncloud.org
or www.chameleoncloud.org. Since the absolute URL is used in the CMS,
the images won't load when using the site via the other domain, since
the CSP only contained 'self' (along with some google domains). This
fix adds both domains, meaning that it should always be able to load the
images.
=> Add our domains to image csp

djangoRT/forms.py, djangoRT/views.py, sharing_portal/models.py, sharing_portal/tasks.py, sharing_portal/views.py
Currently the workflow of creating a new version from an artifact
is busted if you are launching it for the first time and you own it.
Probably this only affects artifacts made before the migration, as
those are the ones that effectively had their local DB state cleared.
Though, this also would affect users who try to launch their own
artifact at the latest version, after publishing that version (because
it creates a new server, w/ a new notebook directory from scratch.)
Requires chameleoncloud/jupyterlab-chameleon#19 and
chameleoncloud/jupyterhub-chameleon#6
=> Fix passing of ownership/artifact meta to jupyter

chameleon_cms_integrations/cms_menus.py
I was unable to find a reverse link for the webinar page from the CMS menu. It looks like the page previously linked-to was used for webinar registration, and we use models from this app on the dashboard. Is this something we use at all anymore? Should it be purged from the user portal?
=> Change the webinar link on user dashboard to link to the same page as the CMS menu

balance_service/enforcement/usage_enforcement.py, balance_service/utils/su_calculators.py, chameleon_cms_integrations/cms_menus.py, sharing_portal/views.py
Balance service doesn't allow user to create/extend lease beyond
active allocation expiration date - even though they have approved
allocation afterward. We fixed the issue by checking the
consecutive approved allocation.
=> fix balance service check_alloc_expiration_date

sharing_portal/trovi.py, sharing_portal/views.py
Any unhandled Trovi exceptions in Portal would previously give an opaque error message to the user, which would not inform them of what actually went wrong. Now, any unhandled Trovi errors will have the API error message forwarded to the user.
`TroviException` is been modified to hold on to more error context.
The `handle_trovi_errors` decorator is implemented to wrap views with a `TroviException` handler, so that any `TroviExceptions` which would otherwise be unhandled are caught, and the API error message is reported to the user. This does not impede any explicit error handling within view functions.
There was some error reporting inside a generator expression that was never actually executed, so errors were never displayed.
The `PATCH` request generated by the sharing form also …
=> Trovi error messages are not very helpful in Portal

sharing_portal/templates/sharing_portal/share.html, sharing_portal/views.py
Since the reviewer is really just reviewing a small allocation request, it is acceptable for them to review daypass requests for artifacts that they don't own. In review functions, we will fetch the artifact with an admin token to ensure that it is visible to portal. The only information that is exposed to the reviewer is the artifact title. This may be subject to change in the future
🏕 Also fixed a couple error messages that were not being output because they were stuck inside generator statements that are never executed.
=> Allow artifact non-owners to review daypass requests

sharing_portal/views.py
The artifact detail page was not properly displaying DOIs. This patch fixes that.
It also alters the previous behavior. The detail page used to show the DOI for whichever version was the most recent, regardless of which version was selected. It now shows the DOI for the selected version only.
The DOI check for making an artifact private on the share page was also removed. Artifacts with DOIs are allowed to be private, but versions with DOIs are still shown.
=> Fix DOI display in Artifact detail page

sharing_portal/views.py
The error handling for artifact edits was not updated in line with the changes from ccee53b5813872a62b210256c2e765d2ce975cf9.
=> Fix crash on artifact edit

sharing_portal/forms.py
There was previously a bug with the tag widget, which would cause it to initially be empty. Because of this, saving the artifact without any changes would cause the tags to be removed from the artifact. Now, the widget will be initialized with whatever tags the artifact had previously.
The widget has also been changed to a multiple-choice checkbox. The multi-select menu thing seems more difficult to use, as it required users to CTRL+Click on multiple options in a tiny scrolling field. It was also not possible to view all of the tags at once in this view.
=> Fix tag widget in artifact edit form

chameleon/settings.py, poetry.lock, pyproject.toml
the celery version here is because bumping 5.1 -> 5.2 breaks something, the issue Anish had the other week.
=> Add cms snippet editor

allocations/tasks.py
End time and hourly-cost errors now actually display what the error is
=> Improve allocation error logging

sharing_portal/forms.py, sharing_portal/templates/sharing_portal/edit.html, sharing_portal/trovi.py, sharing_portal/views.py
Users will now be able to assign and unassign roles from users when editing their artifacts.
The roles function very similarly to the authors, where new input fields are added statically.
=> Add roles to artifact edit form

projects/static/projects/js/bulk_remove.js, projects/templates/projects/bulk_remove_modal.html, projects/templates/projects/view_project.html, projects/views.py
Managing users will now be able to remove all non-manager users with a single button click. It is very similar to the existing bulk add users button.
=> Add bulk remove users button to project page

balance_service/enforcement/exceptions.py, balance_service/enforcement/usage_enforcement.py, chameleon/settings.py
`LeasePastExpirationError` is not sending the right message on raising the exception
Fix `EnforcementException` to use the message of subclass
when a `message` is not passed, it will be `None` and it overwriting `self.message`. This fix will only overwrite it if `message` is passed with contents.
=> fix enforcement exception message

projects/templates/projects/add_publications.html
The guidelines page will look like the above after the changes.
Removed the line that asks users to check for duplicates(this should be done by us)
Removed the line that lets users know how to cite chameleon
=> reformat guidelines for add project page

balance_service/utils/openstack/keystone.py, balance_service/views.py
Currently, balance-service API calls are POST calls with `auth_url` in `request.body`. But `get_project_allocation` is a GET call `authenticate` wrapper around fails because `auth_url` is not present in body as GET call does not have body. 
This change is in `authenticate` to look for `auth_url` from headers if GET request.
```
[DJANGO] INFO django.server.log_message: "GET /api/balance_service/1119 HTTP/1.1" 301 0
[DJANGO] ERROR balance_service.utils.openstack.keystone.load_from_request: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
File "/project/balance_service/utils/openstack/keystone.py", line 24, in load_from_request
context = json.loads(request.body).get("context", {})
File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
return …
```
=> fix for get request not having auth-url in request

projects/admin.py, projects/pub_views.py
When a user uploads a publication. Save the publication along with source
Show `id` field of publication in admin page
=> Publications add source fix

allocations/tasks.py
After Allocation statuses are updated, there is an additional check for allocations that have inconsistent status between Portal and Keycloak
=> Add consistency check to allocation tasks

projects/models.py, projects/pub_views.py, projects/templates/projects/view_publications.html
override delete publication method to change the status of the pub to be deleted
show publication status on the user list publications page
add blank=True to user publication source approved with - so the admin form does not have it as required
trello task - https://trello.com/c/HtV9BDCH/622-publications-admin-page-is-missing-columns
=> override delete publication method to change the status of the pub to be deleted

projects/models.py, projects/pub_views.py, projects/user_publication/citation.py, projects/user_publication/deduplicate.py, projects/user_publication/gscholar.py, projects/user_publication/publications.py, projects/user_publication/utils.py
Fixed a critical issue where `PublicationSource.SCOPUS` needs to be used instead of `Publication.SCOPUS`
Minor formatting fixes
Fixed the duplicate notification issue by changing the year to string `str(pub1.year) != str(pub2.year)` I am not sure why this is happening - this might be because `create_from_bibtex` is creating the model with year in string
Fixes `is_null` to `isnull`
=> Fixes after run pubs

projects/forms.py, projects/pub_views.py
Improve Bibtex Error Messages with Field Indication AddBibtexPublicationForm
=> Improve Bibtex Error Messages with Field Indication

projects/admin.py, projects/models.py, projects/views.py, sharing_portal/views.py
display invite url in admin page of invitation
Resend invitation to multiple invitations (action)
This change so when a user did not receive a invitation for somereason, we can initate a resend so they can use it
use get_invite_url from invitation models in sharing views
=> Invitation admin features

sharing_portal/templates/sharing_portal/detail.html, sharing_portal/templates/sharing_portal/includes/stats.html
The artifact details page shows the version's stats which is confusing as the list page shows the artifact's stats and the details page shows different numbers
Also, update the tooltip for the artifact to show 'last updated at' 
Do not show the last update and version count for version stats
=> Artifact stats detail page confusion fix

.github/workflows/ci.yml
GitHub CI actions fails when installing cosign with error
`Unable to validate cosign version: 'v2.0.2'`
This fix will use the main branch of cosign while explicitly using the v2.0.2
Failed CI run - https://github.com/ChameleonCloud/portal/actions/runs/6735289506/job/18317029790#step:4:247
=> using the version explicitly to eliminate the version validation error

sharing_portal/static/sharing_portal/index.js, sharing_portal/templates/sharing_portal/index.html
- Making another request is very slow as it involves reloading the whole webpage to get the query filter from the URL
- Using a button tag with a badge image inside it
Not a huge visual change, it is there if you look for it. 
Before 
After
=> Add the badge filter to search the DOM instead of making another request

docker-compose.yml
This change comes after a portal outage where celery did not come back on and new approved user projects were not moved to the active state.
=> Added restart=always directive to celery docker-compose entry

allocations/admin.py
This does not replace the existing allocatins approval page
Read only and cannot be used to change details
This is done so project manager can look at allocations and use that data to get insights into them
=> Allocations admin view (read only)

projects/templates/projects/view_project.html
Show gear icon only if the user logged in has manager access level
or show the gear icon for the user itself - so they can remove themselves from the project
Show role drop down only if the logged in user has manager access level
Added edit column name for the gear icon column
=> Clean up membership page - member table

projects/views.py
This occurs, when user role needs to be changed to 'manager' and they currently do not have ChargeBudget set.
If the charge budget for a user that needs to be a manger is not set, ignore the exception and continue with the request/response
=> Pass when user is a manager and does not have a budget created

.github/workflows/ci.yml
Looks like they fixed here - https://github.com/ossf/scorecard-action/issues/998
updating to a newer verison should not be a problem, so bumping up the verison of cosign
=> bump ga:cosign install fails in github action runner - fix version

.github/workflows/ci.yml, sharing_portal/views.py
When creating daypass project users encountered error like this
`TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tag'`
This issue started after this update - https://github.com/ChameleonCloud/portal/commit/f1ec9cc86c707cdaa8a382190b47c96d5286c32a
=> Fix daypass projects to use daypass tag

.env.sample, chameleon/edge_hw_discovery_api.py, chameleon/settings.py, chameleon/templates/edge-hw-discovery/resources.html, chameleon/urls.py, chameleon/views.py, docker-compose.yml
https://github.com/ChameleonCloud/edge-hw-discovery/commit/c2794dca7136a6c33a28feef72028cc69e5623a9 commit description contains an overview of what is done and what can be added
=> Soufianej edge hw discovery page v1.0

projects/user_publication/deduplicate.py, projects/views.py
When a duplicate is marked as duplicate of a original, Update original as approved if the duplicate is originally Approved This would happen when original is a preprint and a user uploaded a published paper in a conference
=> If Dup pub is approved, update original

util/keycloak_client.py
By default, keycloak has:
Query param max: Maximum results size (defaults to 100)
=> Add max paramter to membership list

projects/templates/projects/view_project.html
Add the total members and an index next to users on the project overview page.
=> Add membership count and index to users on project page

projects/views.py
If a user was added/removed or a request accepted, the membership list would not show updates. This is especially evident with the new membership count being displayed.
=> Add check to refetch project membership if changed

sharing_portal/urls.py, sharing_portal/views.py
This will allow the new external trovi dashboard to integrate and use our authoritative badges.
Response structure:
```
{
"badges": [
{
"name": "chameleon",
"description": "for chameleon supported",
"redirect_link": ""
},
{
"name": "reproducible",
"description": "repto badge",
"redirect_link": ""
}
],
"artifact_badges": [
{
"artifact_uuid": "1",
"badge": "chameleon"
}
]
}
```
=> Add API for badges

projects/migrations/0017_add_chameleon_publications_and_pi_aliases.py, projects/views.py, sharing_portal/views.py
This fixes a bug where managers could do what they were supposed to. It seems this is caused by having 2 scopes in keycloak: `manage` and `manager-members`. We may have differentiated this at one point, but now we do now, there are PIs, managers, and members.
This introduces a class UserPermissions that we can use to set these, rather than having to parse keycloak scopes everywhere we want to use permissions.
This also fixes a small bug in a migration.
=> Refactor user permissions

poetry.lock, pyproject.toml
Django's built in module was removed in 4.0, and so this external library must now be included to continue to use memcached.
https://docs.djangoproject.com/en/5.1/topics/cache/#memcached
=> Add memcached library

allocations/admin.py, appliance_catalog/admin.py, blog_comments/admin.py, chameleon/admin.py, projects/admin.py, projects/models.py, projects/views.py, sharing_portal/views.py, user_news/admin.py
This adds some missing admin pages, and makes existing ones more useful with filters and searches.
=> Update admin pages

chameleon_cms_integrations/cms_menus.py
If a user is authenticated, they are correctly redirected to the "logged in" form, so it's safe to always link to guest form. I
In case users were using this button to go to "My tickets" instead of submitting a new one, it now conditionally updates the menu bar link to handle this.
=> Fix help desk button for logged out users.

appliance_catalog/admin.py
We need to return some value by these methods always. I can't find a release note that explains this change, so I assume the prior functionality was not working and unnoticed.
=> Fix appliance admin form

chameleon_mailman/models.py, chameleon_mailman/tasks.py, user_news/models.py
This reformats the outage email (both reminder and new/update emails) to include timezone in Chicago and UTC time, for example '2015-07-01 15:00 CDT  (20:00 UTC)'.
=> Add timezone info to outage emails

allocations/tasks.py
Adds a link to the user's project in allocation renewal reminder email.
=> Add project link in renewal email

allocations/tasks.py, chameleon/settings.py, chameleon/tasks.py, projects/user_publication/gscholar.py, projects/user_publication/publications.py, projects/user_publication/scopus.py
This fixes some general issues with tasks and the pub import tasks.
- Removes unneeded logged in the consistency check. This hasn't been needed for a long time.
- Removes check charge task. Since portal can't connect to the openstack DBs, this does nothing but generate errors. See the commit for more details, but it means that we are slightly overcharging a few users.
- Changes the pub import tasks. I'm not sure why it was working locally for me before, and wasn't running when staged on dev. With these changes, things are working better.
=> Task cleanup

chameleon/templates/dashboard.html, chameleon/views.py, djangoRT/rtUtil.py, djangoRT/templates/djangoRT/ticketList.html, djangoRT/views.py
If the helpdesk isn't working, show an error message instead. This only checks on the ticket list pages. The other ticket pages will show the normal error page. 
The main improvement is this fixes the dashboard loading if RT is not configured or is down.
=> Fix overview/help desk loading issues

.env.sample, Makefile, chameleon/settings.py, docker-compose.yml
This fixes debug logs, `docker-compose` -> `docker compose`, and some default env variables. Also removes phpmyadmin, since I don't think anyone uses it, and referenceapi since that container image can't be pulled.
=> Fix config for local dev

.gitignore, sharing_portal/templates/sharing_portal/includes/artifact_cards.html, sharing_portal/templates/sharing_portal/index.html, sharing_portal/trovi.py, sharing_portal/views.py
This adds AJAX pagination to trovi. We must still render server side,
since it would take too much development time to properly handle this
in the frontend. We can't do a typical pagination, with page buttons
since the Trovi API doesn't support this, and that would break
searching. So now it makes repeated requests for artifacts, and portal
responds with SSRed artifact cards.
=> Improve trovi page with paginated API calls
